"""Plot instantaneous twist geometry and a finite screw trajectory."""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


COLORS = {
    "blue": "#2196F3",
    "green": "#4CAF50",
    "orange": "#FF9800",
    "purple": "#9C27B0",
    "gray": "#607D8B",
}


def main() -> None:
    fig = plt.figure(figsize=(11.5, 5.2), constrained_layout=True)

    ax = fig.add_subplot(1, 2, 1)
    axis_point = np.array([0.35, 0.25])
    point = np.array([1.55, 1.15])
    omega_cross_r = np.array([-0.9, 1.2])
    translation = np.array([0.75, 0.15])
    total = omega_cross_r + translation

    ax.scatter(*axis_point, s=95, color=COLORS["purple"], zorder=4)
    ax.plot([axis_point[0], point[0]], [axis_point[1], point[1]], "--", color=COLORS["gray"])
    ax.scatter(*point, s=75, color="#263238", zorder=4)
    ax.quiver(*point, *omega_cross_r, angles="xy", scale_units="xy", scale=1,
              color=COLORS["blue"], width=0.012, label="rotation contribution")
    ax.quiver(*point, *translation, angles="xy", scale_units="xy", scale=1,
              color=COLORS["green"], width=0.012, label="translation contribution")
    ax.quiver(*point, *total, angles="xy", scale_units="xy", scale=1,
              color=COLORS["orange"], width=0.014, label="point velocity")
    ax.annotate("axis point", axis_point, axis_point + np.array([-0.35, -0.28]), color=COLORS["purple"])
    ax.annotate("tracked point", point, point + np.array([0.08, -0.25]), color="#263238")
    ax.set(xlim=(-0.2, 2.8), ylim=(-0.2, 2.9), xlabel="x", ylabel="y",
           title="Instantaneous twist: rotation + translation")
    ax.set_aspect("equal")
    ax.grid(alpha=0.22)
    ax.legend(loc="upper right", fontsize=8)

    ax3 = fig.add_subplot(1, 2, 2, projection="3d")
    theta = np.linspace(0, 3.6 * np.pi, 300)
    radius = 0.8
    pitch_per_radian = 0.12
    x = radius * np.cos(theta)
    y = radius * np.sin(theta)
    z = pitch_per_radian * theta
    ax3.plot(x, y, z, color=COLORS["blue"], linewidth=2.5, label="point trajectory")
    ax3.plot([0, 0], [0, 0], [-0.2, z[-1] + 0.25], "--", color=COLORS["purple"], linewidth=2,
             label="screw axis")
    sample = 175
    tangent = np.array([-radius * np.sin(theta[sample]), radius * np.cos(theta[sample]), pitch_per_radian])
    tangent = tangent / np.linalg.norm(tangent) * 0.8
    ax3.quiver(x[sample], y[sample], z[sample], *tangent, color=COLORS["orange"], linewidth=2)
    ax3.scatter([x[0]], [y[0]], [z[0]], color=COLORS["green"], s=55, label="start")
    ax3.set(xlabel="x", ylabel="y", zlabel="z", title="Finite motion generated by one constant twist")
    ax3.set_box_aspect((1, 1, 1.2))
    ax3.legend(loc="upper left", fontsize=8)
    ax3.view_init(elev=24, azim=36)

    output = Path(__file__).resolve().parents[1] / "public/robot_twist_screw_motion.png"
    fig.savefig(output, dpi=160, facecolor="white")
    print(output)


if __name__ == "__main__":
    main()
